### ISSUE TITLE
Add committee_type filter to schedules/schedule_a endpoint

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/openFEC#3248] opened 2018-06-28 16:49 UTC
**What we're after:** In order to make it possible for users to search by committee type on the `All receipts` and `Individual contributions` data tables, we need to add a committee_type search filter to the schedules/schedule_a endpoint. 

Similar work: #3449 

Relevant issue: https://github.com/fecgov/fec-cms/issues/2129
Front-end WIP PR: https://github.com/fecgov/fec-cms/pull/2150

**Completion criteria:**

- [ ] Add the filter to `args.py`
- [ ] Add test
- [ ] Add to the release notes

**Comment by rjayasekera** [comment] 2018-07-16 02:22
After looking at the back end query committee_type field is not directly associated with the model (disclosure.fec_fitem_sched_a) itself. It is available in ofec_committee_history_mv

fec_fitem_sched_a table make two joins to ofec_committee_history_mv using committee_id (to get recepient information) and clean_contbr_id (to get contributor information)

Filter by committee_type is not straight forward since this field is not in ScheduleA model itself. I'll pair with @vrajmohan on this Monday and work with him on this issue.

`
SELECT ofec_committee_history_mv_1.committee_type, ofec_committee_history_mv_1.committee_type_full,
ofec_committee_history_mv_2.committee_type, ofec_committee_history_mv_2.committee_type_full, disclosure.fec_fitem_sched_a.cmte_id, disclosure.fec_fitem_sched_a.rpt_yr, disclosure.fec_fitem_sched_a.rpt_tp, disclosure.fec_fitem_sched_a.image_num, disclosure.fec_fitem_sched_a.line_num, disclosure.fec_fitem_sched_a.tran_id, disclosure.fec_fitem_sched_a.file_num, disclosure.fec_fitem_sched_a.cmte_nm, disclosure.fec_fitem_sched_a.entity_tp  
FROM disclosure.fec_fitem_sched_a LEFT OUTER JOIN ofec_committee_history_mv AS ofec_committee_history_mv_1 ON disclosure.fec_fitem_sched_a.clean_contbr_id = ofec_committee_history_mv_1.committee_id AND disclosure.fec_fitem_sched_a.rpt_yr + disclosure.fec_fitem_sched_a.rpt_yr % 2 = ofec_committee_history_mv_1.cycle LEFT OUTER JOIN ofec_committee_history_mv AS ofec_committee_history_mv_2 ON disclosure.fec_fitem_sched_a.cmte_id = ofec_committee_history_mv_2.committee_id AND disclosure.fec_fitem_sched_a.rpt_yr + disclosure.fec_fitem_sched_a.rpt_yr % 2 = ofec_committee_history_mv_2.cycle 
-- WHERE disclosure.fec_fitem_sched_a.two_year_transaction_period = 2018 LIMIT 1;
WHERE disclosure.fec_fitem_sched_a.cmte_id = 'C00321802' and disclosure.fec_fitem_sched_a.two_year_transaction_period = 2018 LIMIT 100;
`

**Comment by rjayasekera** [comment] 2018-07-17 12:17
In /openFEC/webservices/common/models/itemized.py
class BaseItemized(db.Model):
    __abstract__ = True
    **committee** = utils.related_committee_history('committee_id', cycle_label='report_year')

class ScheduleA(BaseItemized):  -- For contributor  information
    __table_args__ = {'schema' : 'disclosure'}
    __tablename__ = 'fec_fitem_sched_a'
   **contributor** = db.relationship(
        'CommitteeHistory',
        primaryjoin='''and_(
            foreign(ScheduleA.contributor_id) == CommitteeHistory.committee_id,
            ScheduleA.report_year + ScheduleA.report_year % 2 == CommitteeHistory.cycle,
        )'''
    )

What we need to do is to filter by committe_type found in the committee join, not from the contributor join

**Comment by rjayasekera** [comment] 2018-07-17 13:17
Can I override the line in class BaseItemized(db.Model): abstract column
        **committee** = utils.related_committee_history('committee_id', cycle_label='report_year')
with the following, 
contributor = db.relationship(
        'CommitteeHistory',
        primaryjoin='''and_(
            foreign(ScheduleA.contributor_id) == CommitteeHistory.committee_id,
            ScheduleA.report_year + ScheduleA.report_year % 2 == CommitteeHistory.cycle,
        )'''
    )
     **committee** = db.relationship(
         'CommitteeHistory',
         primaryjoin='''and_(
             foreign(ScheduleA.committee_id) == CommitteeHistory.committee_id,
             ScheduleA.report_year + ScheduleA.report_year % 2 == CommitteeHistory.cycle,
         )'''
     )

**Comment by rjayasekera** [comment] 2018-07-19 10:02
Continue to working on this with Vraj.  Basic query is done by modifying the query with a `has` clause.
This will create a sub query to retrieve records from committee_history table
`query = query.filter(self.model.committee.has(models.CommitteeHistory.committee_type == kwargs['committee_type'][0].upper() ))`

One think I noticed after the change was degraded performance.  And also the query does not work or taking long time to execute if committee_id is not passed.  

Since we are querying sched_a table with millions of records, can we make the committee_id a mandatory field?

**Comment by lbeaufort** [comment] 2018-07-19 10:05
@rjayasekera we can't require committee ID - that defeats the use case of "make it possible for users to search by committee type"

**Comment by rjayasekera** [comment] 2018-07-19 10:08
After seeing how this API is get called from the front-end we cannot make the committee_id a required field.  The user want to see all the committees received contributions from the `individual contribution` page, and then should be able to filter by `Recipient committee type`

**Comment by rjayasekera** [comment] 2018-07-19 10:18
We are going to try a new approach for the sub query, using Sqlalchemy aliased, and contains_eager functions.
```
committee_committee_history_alias = aliased(models.CommitteeHistory)
        contributor_committee_history_alias = aliased(models.CommitteeHistory)
```
And filter the results by committee_type
```
if kwargs.get('committee_type'):
            query = query.filter(committee_committee_history_alias.committee_type == kwargs.get('committee_type'))
```

Query performance is much improved now.  Thanks @vrajmohan

**Comment by vrajmohan** [comment] 2018-07-20 16:16
While the linked PR provides some direction for the solution, we need to proceed carefully:
1. We are refactoring the existing query and filters and should ensure that we are not breaking any fucntionality
2. We should review existing tests and perhaps add tests where there is inadequate coverage.
3. We should add tests for the `committee_type` filter.
4. We should evaluate performance. We may need to add an index on `committee_type` filter.
5. We should examine the rationale for why some committee columns are _already merged_ into the underlying materialized view while others are only available through a `JOIN`.
6. We should confirm that the filter by `sub_id` does not need to be supported. It may be useful to see if it was intended to be supported and was accidentally dropped.

**Comment by rjayasekera** [comment] 2018-07-23 00:11
I called the schedules/schedule_a end point with several committee_types and cycle = 2018.  API is returning results quickly for committee_types 'Q', 'P', 'H', 'S' 

For the other committee _types results were not returned or the query is taking very long time.

To test the performance creating couple of indexes on public.ofec_committee_history_mv (committee_type and cycle,committee_type)

**Comment by rjayasekera** [comment] 2018-07-24 19:12
Changed the query to use two_year_transaction_period instead of 
```
ScheduleA.report_year + ScheduleA.report_year % 2 == CommitteeHistory.cycle
ScheduleA.two_year_transaction_period  == CommitteeHistory.cycle
```
And also created couple of combined indexes on ofec_committee_history_mv.   
Queries are running little faster when committee_type not found. But still performance is not acceptable. 

Indexes are not used when ScheduleA.report_year + ScheduleA.report_year % 2 is used as join condition.

```
select * 
FROM disclosure.fec_fitem_sched_a 
    LEFT OUTER JOIN ofec_committee_history_mv AS ofec_committee_history_mv_2 
        ON disclosure.fec_fitem_sched_a.cmte_id = ofec_committee_history_mv_2.committee_id 
        AND disclosure.fec_fitem_sched_a.two_year_transaction_period = 
                ofec_committee_history_mv_2.cycle 
LEFT OUTER JOIN ofec_committee_history_mv AS ofec_committee_history_mv_1 
    ON disclosure.fec_fitem_sched_a.clean_contbr_id = ofec_committee_history_mv_1.committee_id 
    AND disclosure.fec_fitem_sched_a.two_year_transaction_period = ofec_committee_history_mv_1.cycle 
WHERE disclosure.fec_fitem_sched_a.two_year_transaction_period = 2018 
    AND ofec_committee_history_mv_2.committee_type = 'D' LIMIT 10;
```
cc @lbeaufort @vrajmohan

**Comment by rjayasekera** [comment] 2018-07-25 00:47
```
Hash Left Join  (cost=37321.93..7102290.72 rows=6305593 width=2687) (actual time=122.638..27385.094 rows=1918639 loops=1)                                
|   Hash Cond: ((fec_fitem_sched_a.two_year_transaction_period = ofec_committee_history_mv_1.cycle) AND ((fec_fitem_sched_a.clean_contbr_id)::text = (ofec_
|   ->  Gather  (cost=13797.72..6073030.29 rows=6305593 width=2057) (actual time=35.527..24127.506 rows=1918639 loops=1)                                   
|         Workers Planned: 4                                                                                                                               
|         Workers Launched: 4                                                                                                                              
|         ->  Hash Join  (cost=12797.72..5441470.99 rows=6305593 width=2057) (actual time=39.928..23764.607 rows=383728 loops=5)                           
|               Hash Cond: ((fec_fitem_sched_a.cmte_id)::text = (ofec_committee_history_mv_2.committee_id)::text)                                          
|               ->  Append  (cost=0.00..4491110.26 rows=11894181 width=1427) (actual time=0.061..19584.055 rows=10568306 loops=5)                          
|                     ->  Parallel Seq Scan on fec_fitem_sched_a  (cost=0.00..0.00 rows=1 width=5683) (actual time=0.001..0.001 rows=0 loops=5)            
|                           Filter: (two_year_transaction_period = '2018'::numeric)                                                                        
|                     ->  Parallel Seq Scan on fec_fitem_sched_a_2017_2018  (cost=0.00..4491110.26 rows=11894180 width=1427) (actual time=0.059..13990.715 
|                           Filter: (two_year_transaction_period = '2018'::numeric)                                                                        
|               ->  Hash  (cost=12731.71..12731.71 rows=5281 width=630) (actual time=37.518..37.518 rows=4824 loops=5)                                     
|                     Buckets: 8192  Batches: 1  Memory Usage: 2403kB                                                                                      
|                     ->  Bitmap Heap Scan on ofec_committee_history_mv ofec_committee_history_mv_2  (cost=250.55..12731.71 rows=5281 width=630) (actual ti
|                           Recheck Cond: ((cycle = '2018'::numeric) AND ((committee_type)::text = 'H'::text))                                             
|                           Heap Blocks: exact=4126                                                                                                        
|                           ->  Bitmap Index Scan on ofec_committee_history_mv_tmp_cycle_committee_type_idx_rj  (cost=0.00..249.23 rows=5281 width=0) (actu
|                                 Index Cond: ((cycle = '2018'::numeric) AND ((committee_type)::text = 'H'::text))                                         
|   ->  Hash  (cost=23255.31..23255.31 rows=17927 width=630) (actual time=86.848..86.848 rows=17997 loops=1)                                               
|         Buckets: 32768  Batches: 1  Memory Usage: 8390kB                                                                                                 
|         ->  Bitmap Heap Scan on ofec_committee_history_mv ofec_committee_history_mv_1  (cost=803.35..23255.31 rows=17927 width=630) (actual time=35.230..
|               Recheck Cond: (cycle = '2018'::numeric)                                                                                                    
|               Heap Blocks: exact=10812                                                                                                                   
|               ->  Bitmap Index Scan on ofec_committee_history_mv_tmp_cycle_committee_type_idx_rj  (cost=0.00..798.87 rows=17927 width=0) (actual time=33.
|                     Index Cond: (cycle = '2018'::numeric)                                                                                                
| Planning time: 4.267 ms                                                                                                                                  
| Execution time: 28055.234 ms```

**Comment by rjayasekera** [comment] 2018-07-25 00:51
For committee_type=C
```
Hash Left Join  (cost=25474.12..5517529.66 rows=302086 width=2687) (actual time=23620.771..23620.771 rows=0 loops=1)                                     
|   Hash Cond: ((fec_fitem_sched_a.two_year_transaction_period = ofec_committee_history_mv_1.cycle) AND ((fec_fitem_sched_a.clean_contbr_id)::text = (ofec_
|   ->  Gather  (cost=1949.91..5445823.01 rows=302086 width=2057) (actual time=23620.769..23620.769 rows=0 loops=1)                                        
|         Workers Planned: 4                                                                                                                               
|         Workers Launched: 4                                                                                                                              
|         ->  Hash Join  (cost=949.91..5414614.41 rows=302086 width=2057) (actual time=23612.920..23612.920 rows=0 loops=5)                                
|               Hash Cond: ((fec_fitem_sched_a.cmte_id)::text = (ofec_committee_history_mv_2.committee_id)::text)                                          
|               ->  Append  (cost=0.00..4491110.26 rows=11894181 width=1427) (actual time=0.063..19974.919 rows=10568306 loops=5)                          
|                     ->  Parallel Seq Scan on fec_fitem_sched_a  (cost=0.00..0.00 rows=1 width=5683) (actual time=0.000..0.000 rows=0 loops=5)            
|                           Filter: (two_year_transaction_period = '2018'::numeric)                                                                        
|                     ->  Parallel Seq Scan on fec_fitem_sched_a_2017_2018  (cost=0.00..4491110.26 rows=11894180 width=1427) (actual time=0.061..14239.462 
|                           Filter: (two_year_transaction_period = '2018'::numeric)                                                                        
|               ->  Hash  (cost=946.75..946.75 rows=253 width=630) (actual time=3.889..3.889 rows=521 loops=5)                                             
|                     Buckets: 1024  Batches: 1  Memory Usage: 163kB                                                                                       
|                     ->  Bitmap Heap Scan on ofec_committee_history_mv ofec_committee_history_mv_2  (cost=15.01..946.75 rows=253 width=630) (actual time=0
|                           Recheck Cond: ((cycle = '2018'::numeric) AND ((committee_type)::text = 'C'::text))                                             
|                           Heap Blocks: exact=514                                                                                                         
|                           ->  Bitmap Index Scan on ofec_committee_history_mv_tmp_cycle_committee_type_idx_rj  (cost=0.00..14.95 rows=253 width=0) (actual
|                                 Index Cond: ((cycle = '2018'::numeric) AND ((committee_type)::text = 'C'::text))                                         
|   ->  Hash  (cost=23255.31..23255.31 rows=17927 width=630) (never executed)                                                                              
|         ->  Bitmap Heap Scan on ofec_committee_history_mv ofec_committee_history_mv_1  (cost=803.35..23255.31 rows=17927 width=630) (never executed)     
|               Recheck Cond: (cycle = '2018'::numeric)                                                                                                    
|               ->  Bitmap Index Scan on ofec_committee_history_mv_tmp_cycle_committee_type_idx_rj  (cost=0.00..798.87 rows=17927 width=0) (never executed)
|                     Index Cond: (cycle = '2018'::numeric)                                                                                                
| Planning time: 4.210 ms                                                                                                                                  
| Execution time: 23800.344 ms ```

**Comment by rjayasekera** [comment] 2018-08-02 19:40
@PaulClark2 @lbeaufort Question about display of committee type. Are we going to display the latest type of the committee (as of today) or latest type of committee for a given cycle?  Assuming committee_type changes even within the election cycle.
cc @vrajmohan @fecjjeng

**Comment by PaulClark2** [comment] 2018-08-02 20:24
@rjayasekera latest type of committee for a given two-year period (cycle). If a committee was type "P" at the end of a two-year period then all transactions disclosed by that committee during that two-year period should be associated with committee type "P."

**Comment by lbeaufort** [comment] 2018-11-06 16:42
PR https://github.com/fecgov/openFEC/pull/3472 has been merged

**Closed by lbeaufort** 2018-11-06 16:42 UTC
Labels: Work: Back-end
