### ISSUE TITLE
[Research] /legal/search endpoint: Fix exact string match to only return exact strings from documents

### ISSUE THREAD

**Issue by patphongs** [fecgov/openFEC#5832] opened 2024-05-14 14:00 UTC
### What we’re after

exact string match to NOT include stem words, but include common words like “to”, “not”, etc.
 We should do more research to see if we can not include stem words and search stop words (if needed) only for exact string match 

Currently the stop words functionality seems to be working as expected ie "reason to believe". Is searching for just a stop word ie "NOT" necessary functionality 

### Related ticket(s)

(Include the tickets that either came before, after, or are happening in tandem with this new ticket)

- [ ] #5830 

### Action item(s)

(These are the smaller tasks that should happen in order to complete this work)

- [ ] research not searching stem words
- [ ] research searching stop words

### Completion criteria

(What does the end state look like - as long as this task(s) is done, this work is complete)

- [ ] We have a plan in place for exact string match changes if needed and ticket for implementation is created

**Comment by pkfec** [comment] 2024-06-05 12:54
https://www.elastic.co/guide/en/elasticsearch/reference/7.4/mixing-exact-search-with-stemming.html#mixing-exact-search-with-stemming

**Comment by patphongs** [comment] 2024-06-05 14:24
@pkfec Here's another example of exact string match not working. When a user tries to search "No reason to believe", they get returned results for "reason to believe" as well. Which is overly inclusive because No is considered a reserved word.

**Comment by pkfec** [comment] 2024-06-06 13:36
> [@pkfec](https://github.com/pkfec) Here's another example of exact string match not working. When a user tries to search "No reason to believe", they get returned results for "reason to believe" as well. Which is overly inclusive because No is considered a reserved word. https://www.fec.gov/data/legal/search/murs/?search_type=murs&sort=&search=%22No+reason+to+believe%22&case_no=&case_respondents=&case_min_open_date=&case_max_open_date=&case_min_close_date=&case_max_close_date=
> 
> Another example issue is with stem words. When someone searches "Commission finds", they get other stem words like "Commission finding", "Commission findings", "Commission find".
> 
> https://www.fec.gov/data/legal/search/murs/?search_type=murs&sort=&search=%22Commission+finds%22&case_no=&case_respondents=&case_min_open_date=&case_max_open_date=&case_min_close_date=&case_max_close_date=


@patphongs We are using an [English analyzer](https://www.elastic.co/guide/en/elasticsearch/reference/7.4/analysis-analyzers.html#analysis-analyzers) in our code, both at the index and field levels. This analyzer includes functionalities such as stemming, stopword identification, as well as keyword and lowercase marking. From the provided example, it's evident that the English analyzer functions as intended by dividing strings into tokens and searching for matching words within documents, in contrast to treating the entire string as a single entity, which may be achieved using the [keyword analyzer.](https://www.elastic.co/guide/en/elasticsearch/reference/7.4/analysis-keyword-analyzer.html)

**Comment by patphongs** [comment] 2024-06-12 17:48
## Elasticsearch test findings
### Search analyzers
- **English:** This is what our API is currently using.
- **Standard:** This is the default analyzer that comes with elasticsearch.
- Key differences between these:
   1. Stop words:
      a. `standard` analyzer: Does not remove stop words. 
      b. `english` analyzer: Removes English stop words to focus on more meaningful terms.
   2. Stemming:
      a. `standard` analyzer: Does not perform stemming.
      b. `english` analyzer: Performs stemming to normalize different forms of a word to a common root.
   3. Optimization:
      a. `standard` analyzer: General-purpose and language-agnostic.
      b. `english` analyzer: Specifically optimized for English text, improving relevance for English-language searches.

### Observations
- The `test-index` must be deleted and recreated each time or you will get duplicate document hits
- The default analyzer is standard. To change the analyzer type, it must be done in the query. For example:
```
{
  "query": {
    "match_phrase": {
      "text": {
        "query": "reason to believe",
        "analyzer": "english"
      }
    }
  }
} 
```
- Elasticsearch  has different query operators: `match` vs `match_phrase`, which is used to search text. Key differences:
   - `match` query
      - **Functionality:** Analyzes the input text and constructs a query for each term independently. 
      - **Analysis:** The input text is analyzed (tokenized, lowercased, etc.), and each term is searched for in the index. The query looks for documents containing one or more of the terms.
      - **Relevance:** Documents that contain more of the terms or higher-frequency terms get a higher score, but the term positions are not considered.
   - `match_phrase` query
      - **Functionality:** The match_phrase query looks for documents containing the exact sequence of terms provided, preserving their order and relative positions. It is useful for phrase searches where the order of words is crucial.
      - **Analysis:** The input text is analyzed, but the terms are then searched for in the exact order they appear in the input, meaning the terms must be adjacent.
      - **Relevance:** Only documents containing the exact sequence of terms, in the same order, are considered a match.

**Comment by pkfec** [comment] 2024-06-13 18:43
## Proximity search 
**What is Proximity search:**
_Its about how close the search strings are to each other. The order of the search terms doesn’t really matter, as long as they occur somehow within the same context._


**Test notes:**
-
**1.** Use search-3.json

  Input: 
``` {
  "query": {
    "match": {
      "text": {
        "query": "penalty AND 30 day"
      }
    }
  }
}
```
  
Output: Returns documents that contains words like penalty AND or 30day. (We noticed the same on our website)
```
{
    "total": {
        "value": 2,
        "relation": "eq"
    },
    "max_score": 0.5680921,
    "hits": [
        {
            "_index": "test-index",
            "_type": "_doc",
            "_id": "k9IgEpAByJ4l5yn9CWhr",
            "_score": 0.5680921,
            "_source": {
                "text": "penalty Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam quis ex neque. 30 day."
            }
        },
        {
            "_index": "test-index",
            "_type": "_doc",
            "_id": "WCAgEpABiIZSrSI0Cx17",
            "_score": 0.52735245,
            "_source": {
                "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. There is a 30 day penalty. Aliquam quis ex neque."
            }
        }
    ]
}
}
```


**2.** Use search-intervals.json with `max_gap`
  
**What is intervals query:**
_[Intervals query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-intervals-query.html#intervals-query-ex-request) returns documents based on the order and proximity of matching terms._

  **What is max_gap:**
_Maximum number of positions between the matching terms. Terms further apart than this are not considered matches. Defaults to -1..
If set to 0, the terms must appear next to each other._

 Input: 
```
{
  "query": {
    "intervals" : {
      "text" : {
        "all_of" : {
          "ordered" : false,
          "intervals" : [
            {
              "match": {
                "query": "30 day penalty",
                "max_gaps" : 0,
                "ordered": false
              }
            }
          ]
        }
      }
    }
  }
}


```
 Output: Result set include document that have exact match string as shown in doc7.json

 {
"took": 232,
"timed_out": false,
"_shards": {
    "total": 5,
    "successful": 5,
    "skipped": 0,
    "failed": 0
},
"hits": {
    "total": {
        "value": 1,
        "relation": "eq"
    },
    "max_score": 0.5,
    "hits": [
        {
            "_index": "test-index",
            "_type": "_doc",
            "_id": "WCAgEpABiIZSrSI0Cx17",
            "_score": 0.5,
            "_source": {
                "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. There is a 30 day penalty. Aliquam quis ex neque."
            }
        }
    ]
}
}

Observations:  When `max_gap` >=12,   2 results were returned

**Comment by patphongs** [comment] 2024-06-18 16:51
Thank you for all of your research so far @pkfec! I have one comment regarding the Elasticsearch relevancy score. I think it is important when implementing proximity type searching. This score helps to determine how well a document matches a given query. 

If we implement proximity search only with the ability to sort by MUR number, there will be a loss of relevance. Meaning regardless of how closely the query terms are positioned within the documents, the results will only display in the order of the MUR number. This would mean reduced relevance as newer MURs are prioritized over how close the query actually matched the terms entered.

**Comment by fec-jli** [comment] 2024-06-24 02:31
———Test **/legal/search/** endpoint with match_phrase on local (06/20/2024)———
Change index_analyzer = "standard" in variable ANALYZER_SETTING
1)update es_management.py line 406: (or remove analysis section, default analyzer=standard)
```
ANALYZER_SETTING = {
    "analysis": {
        "analyzer": {
            "default": {
               "type": "standard"
            }
        }
    },
    "highlight.max_analyzed_offset": 60000000,
}
```

2)setup and start local Elasticsearch service

3)re-create index
python cli.py delete_index case_index
python cli.py create_index case_index

Check analyzer setting: http://localhost:9200/_settings

4)load 3 sample murs
python cli.py load_current_murs 8184 (without phrase: “reason to believe”)
python cli.py load_current_murs 8213(content phrase: “reason to believe”)
python cli.py load_current_murs 8201(content phrase: “reason to believe”)

5)Test **/legal/search/** endpoint, start server: flask run
Test 1: Existing code (use **query_string**):
Return all 3 murs (8184, 8213 and 8201)
http://127.0.0.1:5000/v1/legal/search/?type=murs&q=reason%20to%20believe

Test 2 Change to **match_phrase** in legal.py, line 256
```
  combined_query.append(
    Q(
       { "match_phrase": { "documents.text":  { "query": q, "analyzer": "standard"}}},
    )
 )

```
Or
```
  combined_query.append(
    Q(
       { "match_phrase": { "documents.text":  { "query": q}}},
    )
 )
```

Return only 2 murs (8213 and 8201), mur 8184 won't return
http://127.0.0.1:5000/v1/legal/search/?type=murs&q=reason%20to%20believe


Test 3 : change search_analyzer=“english”
```
  combined_query.append(
    Q(
       { "match_phrase": { "documents.text":  { "query": q, "analyzer": "english"}}},
    )
 )
```

Return empty, because “search_analyzer” not match index_analyzer
http://127.0.0.1:5000/v1/legal/search/?type=murs&q=reason%20to%20believe

**Comment by markdboyd** [comment] 2024-06-25 17:23
@pkfec One note: you don't have to specify `max_gaps` when constructing an intervals query. Without `max_gaps`, result scores and order is determined by proximity, but no results are excluded if the search phrases are too far apart

**Comment by tmpayton** [comment] 2024-07-09 14:23
Closing this ticket pending testing

**Closed by tmpayton** 2024-07-09 14:23 UTC
Labels: Work: Back-end
