### ISSUE TITLE
Fields in results returned by the /committee/{committee_id}/reports/ endpoint are mis-mapped.

### ISSUE THREAD

**Issue by AmyKort** [fecgov/openFEC#3435] opened 2018-10-12 15:12 UTC
It appears as though some (but not all) fields in the results returned by the /committee/{committee_id}/reports/ endpoint are mis-mapped.

An example report is: https://api.open.fec.gov/v1/committee/C00501197/reports/?api_key=DEMO_KEY&year=2018&report_type=Q2 compared to http://docquery.fec.gov/cgi-bin/paper_forms/C00501197/1250782/

Some fields I've noticed are giving different results are:

total_disbursements_ytd
other_disbursements_ytd
transfers_to_other_authorized_committee_ytd
other_receipts_ytd

**Comment by hcaofec** [comment] 2018-10-18 18:58
The discrepancy here is caused by the mis-mapping in the data files sent to informatica.  Salient has a resolution for this. Once the data files are fixed, the discrepancy will be fixed too.

**Comment by jwchumley** [comment] 2018-11-05 19:16
The YTD columns have been updated in DEV and reviewed and are being updated in PROD now.

**Comment by hcaofec** [comment] 2018-11-08 15:18
Looks like the data has been restored.  Here is the result of checking the example in this ticket:
https://api.open.fec.gov/v1/committee/C00501197/reports/?api_key=DEMO_KEY&year=2018&report_type=Q2 
**compared to** http://docquery.fec.gov/cgi-bin/paper_forms/C00501197/1250782/

Column|API|Image
------|------|----
total_disbursements_ytd|10100820.2699999996|10098206.01
other_disbursements_ytd|21042.19|21067.19
transfers_to_other_authorized_committee_ytd|0|0
other_receipts_ytd|3082.2|3082.20

**Comment by jwchumley** [comment] 2018-11-08 16:32
Yes. The update scripts ran this morning.

**Closed by jwchumley** 2018-11-08 16:32 UTC
Labels: Bug, External Review, Needs grooming, Work: Back-end
