### ISSUE TITLE
Inconsistency between information displayed on data page and download file

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/openFEC#3353] opened 2018-09-02 19:57 UTC
**Reported by**: https://github.com/fecgov/FEC/issues/7693

**What we are after**: The data page should display all the rows that are included in the download file.

**Why we are after it**: The data page should display all request data to users. The inconsistency between the data page and the download file undermines user confidence. 

**Current state**: 
![0ae61d62-548c-45fe-a96f-325f90521b7a](https://user-images.githubusercontent.com/11817734/44960263-1f816280-aeca-11e8-9acd-1f604f20c13e.jpeg)

![c6db719c-2a66-4b74-92a0-861b75d16965](https://user-images.githubusercontent.com/11817734/44960276-56577880-aeca-11e8-9fb1-b6c8b0ee8ce6.jpeg)

**Business completion criteria**: 
- [x] understand and explain the cause of the discrepancy 
- [ ] make the data page row count and the download row count the same (technical completion criteria)

**Technical completion criteria**: 
- [ ] Get rid of `sort_hide_null=true` and change to `=false` and see if it's fixed
- [ ] Check, and if necessary, correct across all datatables for consistency

**Comment by patphongs** [comment] 2018-09-04 19:41
This is related to #3104

**Comment by PaulClark2** [comment] 2018-09-05 05:16
It might be related to #3104. The symptoms are different. The number of rows in the data table don’t match the number of rows in the download file.. We are not displaying all the results to  the user in the data table. The only way a user can see all the results is to download the file.

**Comment by patphongs** [comment] 2018-09-05 14:46
@PaulClark2 The devs talked about this yesterday and it is related to #3104. The count estimates seem to be inaccurate across the board and this is another example of inaccurate counts. I'm going to close this as a duplicate and have already linked this issue to the counts issue ticket.

**Comment by PaulClark2** [comment] 2018-09-05 14:50
@patphongs this isn’t really about the counts. The data table displays 2 rows the download contains 7 rows.  Which answer is correct?

**Comment by patphongs** [comment] 2018-09-05 15:02
@PaulClark2 I see what you're saying, I'll ask the team about this.

**Comment by patphongs** [comment] 2018-09-05 17:29
@PaulClark2 Did some additional investigation and what is happening is that there is an additional flag for `sort_hide_null=true` in the API request (See below). That means that in the datatable, any records with null values will not be returned, hence why you only see 2 rows. 

I believe this flag is turned on when we want to save on performance especially on receipt and disbursement queries. But for the downloads, it retrieves null records as well and returns that in the CSV. I guess the question is, do we want the download to also hide null values?

https://api.open.fec.gov/v1/candidates/?api_key=5yyI90SU3Xb73TVlv4wrEhQxYcCwMWCywQiGdYbJ&sort_hide_null=true&q=jeff+brown&sort=-first_file_date&per_page=30&page=1

**Comment by AmyKort** [comment] 2018-09-14 19:27
Let's explore the possibility that was raised today of providing users the option to pick a data set that contains null committees and another option that excludes those results.

**Comment by patphongs** [comment] 2018-09-18 14:45
Some ideas for this that was discussed. @AmyKort @PaulClark2 can you please help make a decision about what the business logic should be and we can proceed from there?

- Creating a toggle so that users can switch show_hide_null
- Keep the business logic the way it is now and leaving nulls inside the downloads
- Remove nulls from downloads

**Comment by lbeaufort** [comment] 2018-10-05 20:46
@PaulClark2 I confirmed that the issue we discussed with the filings data table count being off stems from the same issue, so I'm not going to enter a separate bug.

We need to:
1) Determine if hiding nulls in the sort column is the desired default behavior on the front end (this doesn't seem ideal but I can look into it more)
2) Modify the API to adjust the counts downward if we're hiding results that have a null value in the sort column

**Comment by patphongs** [comment] 2018-10-26 14:58
## We need some business logic clarification:

### What is sort_hide_null
sort_hide_null toggles rows on and off that have sort column that is null. By default the `sort_hide_null=true` and therefore will hide any null rows from the sorted column. If we turn this off and have `sort_hide_null=false` it will return all data.

### Possible problems:
- If we set `sort_hide_null=false` by default, we will get null rows returned for the sorted column. 

### Business expert questions @PaulClark2 @jwchumley @JonellaCulmer:
- [ ] We need to be consistent with our exports. Currently our exports will return null data. The front-end view will not. Do we want to turn on null results for the front end datatable view? 
- [ ] Will this make the data that is returned confusing and sloppy? Because it's difficult to go through hundreds and possibly thousands of rows of sorted null data on the front end?

### Possible technical  concerns:
- [ ] Need to investigate if this will effect performance because there may be a lot of null data. Database experts should query the data to see how many null rows are returned for sorted columns.

**Comment by lbeaufort** [comment] 2018-10-29 17:32
@patphongs in this example,  the front-end view should return 7 rows, not 2.

**Comment by PaulClark2** [comment] 2018-10-29 17:37
Agreed, the front end should show seven rows.

**Comment by lbeaufort** [comment] 2018-10-29 20:05
Issue moved to [fecgov/fec-cms #2481](https://github.com/fecgov/fec-cms/issues/2481) via [**ZenHub**](https://www.zenhub.com/)

**Closed by lbeaufort** 2018-10-29 20:05 UTC
Labels: Bug, Needs grooming, Work: Front-end
